apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wildfly-op-leader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wildfly-op-leader-role
subjects:
- kind: ServiceAccount
  name: wildfly-operator

